---
# Retrieve the current hostname, because {{ ansible_hostname }} still contains the old name
 - shell: hostname
   register: current_hostname

 - name: Add MariaDB repository
   apt_repository: repo='{{ repository.url }}' state=present

 - name: Add MariaDB repository keys
   apt_key: keyserver={{ repository.keyserver }} id={{ repository.id }} state=present

 - name: Install MariaDB
   apt: pkg={{ item }} state=latest update_cache=true
   with_items:
      - mariadb-server
      - python-mysqldb # Used by ansible

 - name: Update root password
   mysql_user: name=root check_implicit_admin=yes
               host={{ item }} password={{ root_password }}
               login_user=root login_password={{ root_password }}
   with_items:
     - "{{ current_hostname.stdout | lower }}"
     - 127.0.0.1
     - ::1
     - localhost

 - name: Remove all anonymous users
   mysql_user: name='' host={{ item }} state=absent
               login_user=root login_password={{ root_password }}
   with_items:
     - "{{ current_hostname.stdout | lower }}"
     - 127.0.0.1
     - ::1
     - localhost

 - name: Create database
   mysql_db: name={{ item.name }} state=present login_user=root login_password={{ root_password }}
   with_items:
       - "{{ databases }}"

 - name: Create user
   mysql_user: name={{ item.user }} password={{ item.password }}
               priv={{ item.name }}.*:ALL state=present
               login_user=root login_password={{ root_password }}
   with_items:
       - "{{ databases }}"
