---

 - name: Add PHP 7 repository key
   apt_key: url={{ repository.key_url }} state=present
   when: repository.key_url
   
 - name: Add PHP 7 repository
   apt_repository: repo='{{ repository.url }}' state=present

 - name: Install PHP 7
   apt: pkg={{ item }} state=latest update_cache=true
   sudo: true
   with_items:
     - "{{ packages }}"
   notify:
     - Start php-fpm

 - name: Set timezone for PHP
   lineinfile: dest=/etc/php/{{ version }}/{{ item }}/php.ini
               regexp=';?date.timezone ='
               line='date.timezone = {{ server.timezone }}'
               state=present
   with_items:
     - cli
     - fpm
   notify:
     - Start php-fpm

 - name: Install Xdebug
   apt: pkg={{ xdebug.package }} state=latest update_cache=true
   sudo: true
   when: xdebug.enable
   notify:
     - Start php-fpm
