---
 - name: Install nginx
   apt: pkg=nginx state=latest update_cache=true
   sudo: true
   notify:
     - Start nginx

 - name: Add H5BP config
   copy: src=h5bp dest=/etc/nginx/ owner=root group=root
   sudo: true

 - name: Disable default configuration
   file: dest=/etc/nginx/sites-enabled/default state=absent
   sudo: true
   notify:
     - Reload nginx

 - name: Add sites config
   template: src={{ item }}.j2 dest=/etc/nginx/sites-available/{{ item }} owner=root group=root
   sudo: true
   with_items:
     - no-host


 - name: Enable sites
   file: src=/etc/nginx/sites-available/{{ item }} dest=/etc/nginx/sites-enabled/{{ item }} state=link
   sudo: true
   with_items:
     - no-host
   notify:
     - Reload nginx
